character_twh = [6, 80, 56]
frame_face_ltwh = [20, 47, 41, 22]
vertical_dark_edge = 5
two_character_spec = 20
x_character_spec = 16
frame_content_ltwh = [60, 50, 144, 16]
text_ltwh = [61, 51, 140, 15]
frame_name_ltwh = [60, 49, 10, 1]
short_key_ltwh = [60, 66, 144, 1]
chapter_title_ltwh = [60, 27, 120, 5]
chapter_subtitle_ltwh = [60, 32, 120, 1]
paragraph_ltwh = [60, 7, 120, 49]
