resolution = [240, 80]
is_force_skipable = false
save_dir = "save"
entre_script = "resource/script_example.fss"
default_bg_img = "resource/bg_0.png"
default_face_img = "resource/default_face_img.png"
preprogress_script = ["resource/script_example.fs"]

[layout]
character_up_edge = 12
character_size = [56, 56]
df_size = [40, 20]
df_lt = [16, 56]
dark_edge = 6
two_character_spec = 48
x_character_spec = 16
dtf_lr_edge = 32
dtf_height = 16
text_lt = [64, 64]
text_size = [136, 14]
