resolution = [240, 80]
is_force_skipable = false
save_dir = "save"
entre_script = "resource/script_example.fss"
default_bg_img = "resource/bg_0.png"
default_face_img = "resource/default_face_img.png"
preprogress_script = ["resource/script_example.fs"]

[layout]
character_up_edge = 12
character_twh = [8, 56, 64] # 16, 56 ,128
vertical_dark_edge = 8 # 12
two_character_spec = 48
x_character_spec = 16
frame_face_ltwh = [16, 58, 44, 22] # 16, 112, 48 48
frame_name_ltwh = [60, 58, 10, 1]
frame_content_ltwh = [60, 59, 144, 20]
text_ltwh = [61,60,140, 19]
short_key_ltwh = [60, 79, 144, 1]
